local picker = require 'picker'
require 'card'

---@class surveil
---@field allCards card[]
---@field trimmedCards card[]?
---@field defaultQuery string?
---@field bulkDataPath string
---@field sortPredicate string?
---@field cacheDir string
---@field curlArgs string
local M = {}
M.loader = require 'loader'
M.opts = require 'opts'
M.cardLists = require 'cardLists'
M.query = require 'query'


---@param opts surveilOpts?
M.setup = function(opts)
  opts = opts or {}


  M.opts.bulkDataPath = opts.bulkDataPath or M.opts.bulkDataPath
  M.opts.defaultQuery = opts.defaultQuery
  M.opts.sortPredicate = opts.sortPredicate
  M.opts.cacheDir = opts.cacheDir or M.opts.cacheDir
end

---Set the query used to filter out entirely unwanted cards, such as art carts and tokens.
---Sets the primary table to the result of the given query.
---@param query string: The query to run.
M.setDefaultQuery = function(query)
  M.opts.defaultQuery = query
  if M.defaultQuery then
    M.cardLists.trimmedCards = M.query.query(M.defaultQuery)
  else
    M.cardLists.trimmedCards = nil
  end
end

---@param field string
M.setSortPredicate = function(field)
  M.opts.sortPredicate = field

  if M.cardLists.allCards then
    M.loader.sortList(M.cardLists.allCards, field)
    if M.cardLists.trimmedCards then
      M.cardLists.trimmedCards = M.query.queryTable(M.cardLists.allCards, M.defaultQuery)
    end
  end
end


---Open the picker window.
---@param prequery string?: Use this to further narrow down cards. Ideal for narrowing by format, color identity for commander, available game types.
---@param allCards boolean?: If true will use all loaded cards, rather than the table of cards generated by the default query. Will still run the prequery, if given.
M.picker = function(prequery, allCards)
  if not M.cardLists.allCards then
    M.loader.loadCards()
  end

  local target

  if allCards then
    target = M.cardLists.allCards
  else
    target = M.cardLists.trimmedCards or M.cardLists.allCards
  end

  if prequery then
    target = M.query.queryTable(target, prequery)
  end

  picker:ShowMenu(target)
end

---Use this to free up processing power without having to restart Neovim.
---Will even unload user lists
M.unloadCards = function()
  M.cardLists.allCards = nil
  M.cardLists.trimmedCards = nil
  vim.print "Unloaded all cards."
end

return M
