local M = {}

---@param opts table?
M.setup = function (opts)

end

---Mostly for internal use but maybe you can get some use out of it.
---@param query string: The query to run, for a full list of currently implemented syntax, please see #FILE#.
---@return table?: The results of the query.
---@param allCards boolean?: If true will use all loaded cards, rather than the table of cards generated by the default query.
M.query = function (query, allCards)

end

---Open the picker window.
---@param prequery string?: Use this to further narrow down cards. Ideal for narrowing by format, color identity for commander, available game types.
---@param allCards boolean?: If true will use all loaded cards, rather than the table of cards generated by the default query. Will still run the prequery, if given.
M.picker = function (prequery, allCards)

end

---Set the query used to filter out entirely unwanted cards, such as art carts and tokens.
---Sets the primary table to the result of the given query.
---@param query string: The query to run.
M.setDefaultQuery = function (query)

end

M.updateCards = function ()

end

M.loadCards = function ()

end

return M
