---@class surveil
---@field allCards table?
---@field trimmedCards table?
---@field defaultQuery string?
---@field bulkDataPath string
---@field sortPredicate string?
local M = {}

local curlArgs = " --header User-Agent:nvim-surveil --header Accept:*/* --silent "
local utils = require'utils'
local querySession = require'query'
local picker = require'picker'
local Set = require'Set'

M.bulkDataPath = vim.fn.stdpath("cache") .. "/oracle_cards.json"

---@param opts table?
M.setup = function (opts)
  opts = opts or {}

  M.bulkDataPath = opts.bulkDataPath or M.bulkDataPath
  M.defaultQuery = opts.defaultQuery
  M.sortPredicate = opts.sortPredicate
end

---Mostly for internal use but maybe you can get some use out of it.
---@param query string: The query to run. For a full list of currently implemented syntax, please see README.md. Returns all cards if empty or nil, respecting allCards.
---@return table?: The results of the query or nil if no cards are loaded. Will return an empty table if there are no results.
---@param allCards boolean?: If true will use all loaded cards, rather than the table of cards generated by the default query.
M.query = function (query, allCards)
  if M.allCards == nil then
    M.loadCards()
  end

  local target

  if allCards then
    target = M.allCards
  else
    target = M.trimmedCards or M.allCards
  end

  if not target then return nil end

  if query == "" or query == nil then
    return target
  end

  return querySession.queryTable(target, query)
end

---Set the query used to filter out entirely unwanted cards, such as art carts and tokens.
---Sets the primary table to the result of the given query.
---@param query string: The query to run.
M.setDefaultQuery = function (query)
  M.defaultQuery = query
  if M.defaultQuery then
    M.trimmedCards = M.query(M.defaultQuery, true)
  else
    M.trimmedCards = nil
  end
end

M.updateCards = function ()
  local tempFileName = os.tmpname()

  local ok, str, code = os.execute("curl https://api.scryfall.com/bulk-data/oracle-cards" .. curlArgs ..  "> " .. tempFileName)

  if not ok then
    print(str .. code)
    return
  end

  local tempFile = io.open(tempFileName)
  if tempFile == nil then
    return
  end
  local json = tempFile:read()

  local jsonObj = vim.json.decode(json, {object = true, array = true})
  os.execute("curl " .. jsonObj.download_uri .. curlArgs .. "-o " .. M.bulkDataPath)
end

M.loadCards = function ()
  local bulkDataFile = io.open(M.bulkDataPath)

  if bulkDataFile then
    local bulkDataJson = bulkDataFile:read("a")
    M.allCards = vim.json.decode(bulkDataJson, {object = true, array = true})
  else
    vim.ui.input({
      prompt = "No card data found, would you like to download card data? [y/N]:",
      default = "n",
    }, function (input)
      if input == "y" or input == "Y" then
        M.updateCards()
        bulkDataFile = io.open(M.bulkDataPath)
        if bulkDataFile then
          local bulkDataJson = bulkDataFile:read("a")
          M.allCards = vim.json.decode(bulkDataJson, {object = true, array = true})
        else
          vim.print("Error loading bulk data.")
        end
      end
    end)
  end

  if M.sortPredicate then
    M.sortList(M.allCards, M.sortPredicate)
  end

  for _, v in pairs(M.allCards) do
    if v.colors then
      v.colors = Set(v.colors)
    end
    if v.color_identity then
      v.color_identity = Set(v.color_identity)
    end
  end

  if M.defaultQuery then
    M.trimmedCards = M.query(M.defaultQuery, true)
  end
end

---@param field string
M.setSortPredicate = function (field)
  M.sortPredicate = field

  if M.allCards then
    M.sortList(M.allCards, field)
    if M.trimmedCards then
      M.trimmedCards = querySession.queryTable(M.allCards, M.defaultQuery)
    end
  end

end

---@param list table
---@param field string
M.sortList = function(list, field)
  if field == "edhrec_rank" then
    table.sort(list, function(a, b)
      local aV = a["edhrec_rank"] or 9999999
      if aV == 0  then
        aV = 9999999
      end

      local bV = b[field] or 9999999
      if bV == 0 then
        bV = 9999999
      end

      return aV < bV
    end)
  else
    table.sort(list, function(a, b)
      local aV = utils.evaluatePT(a[field])
      local bV = utils.evaluatePT(b[field])

      return aV < bV
    end)
  end

end

---Open the picker window.
---@param prequery string?: Use this to further narrow down cards. Ideal for narrowing by format, color identity for commander, available game types.
---@param allCards boolean?: If true will use all loaded cards, rather than the table of cards generated by the default query. Will still run the prequery, if given.
M.picker = function (prequery, allCards)
  if not M.allCards then
    M.loadCards()
  end

  local target

  if allCards then
    target = M.allCards
  else
    target = M.trimmedCards or M.allCards
  end

  if prequery then
    target = querySession.queryTable(target, prequery)
  end

  picker:ShowMenu(target)
end

---Use this to free up processing power without having to restart Neovim.
---Will even unload user lists
M.unloadCards = function ()
  M.allCards = nil
  M.trimmedCards = nil
  vim.print"Unloaded all cards."
end

return M
